# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.

      Write-Host "pepe"
      #$PAT = "INSERT PAT"
      #$url = "https://dev.azure.com/matiasd0832/NewPracticeProject/_apis/wit/workitems?ids=352,353,354&api-version=6.0"
      #$user = ""
      #$token = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $user, $PAT)))

      #$header = @{authorization = "Basic $token"}

      #$response = Invoke-RestMethod -Method Get -Headers $header -Uri $url

      #$response | ConvertTo-Json

      #$response.value.fields
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
