# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $fecha = Get-Date
      $PAT = "vfe5wmddwpun3azwicjnpjna4jampo32hfsx6uqt7h3u3fvmwm4a"
      $url = "https://dev.azure.com/matiasd0832/NewPracticeProject/_apis/wit/workitems?ids=352,353,354&api-version=6.0"
      $headers = @{Authorization=("Basic $PAT")}
      Invoke-RestMethod -Method Get -Headers $headers -Uri $url
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
